---
- name: "openssh-server:template:/etc/ssh/sshd_config"
  template:
    src: "openssh-server/sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    mode: "644"
    owner: "root"
    group: "root"
  become: true
  tags:
    - openssh-server[config]

- name: "openssh-server:service:restarted"
  service:
    name: "ssh"
    sleep: 3
    state: "restarted"
  become: true
  tags:
    - openssh-server[service]
