#!/usr/bin/env sh

# see: https://github.com/prometheus/prometheus/blob/main/Dockerfile
# see: https://prometheus.io/docs/prometheus/latest/storage/#operational-aspects
#
# note: environment variable substitution is NOT supported in the prometheus configuration file
# see: https://github.com/prometheus/prometheus/issues/2357#issuecomment-810876410
#
# --enable-feature=remote-write-receiver  -> HTTP /api/v1/write
# --web.enable-lifecycle                  -> POST /-/reload (signal: SIGUP)
#                                            POST /-/quit   (signal: SIGTERM)
# --enable-feature=expand-external-labels ->

cd '{{ prometheus.home }}'
exec \
  s6-envdir -I /etc/services.d/prometheus/env \
  s6-setuidgid '{{ prometheus.user }}' \
  prometheus \
    --config.file='{{ prometheus.config_file }}' \
    --web.console.libraries='{{ prometheus.home }}/console_libraries' \
    --web.console.templates='{{ prometheus.home }}/consoles' \
    --web.listen-address='0.0.0.0:9090' \
    --web.telemetry-path='/metrics' \
    --web.enable-lifecycle \
    --storage.tsdb.path='/var/run/prometheus/tsdb/data' \
    --storage.tsdb.retention.time='1h' \
    --storage.tsdb.retention.size='256MB' \
    --storage.tsdb.wal-compression \
    --enable-feature=expand-external-labels \
  2>&1
