---
ansible_ignore_errors: false
ansible_ignore_include_errors: false
ansible_retry_count: 5
ansible_retry_delay: 60

ansible_debug_vars: true
ansible_debug_vars_list:
  - "inventory_hostname"
  - "ansible_hostname"
  - "ansible_distribution"
  - "ansible_distribution_release"
  - "ansible_distribution_version"
  - "ansible_distribution_major_version"
  - "ansible_python_interpreter"
  - "ansible_playbook_python"
  - "ansible_python_interpreter"

ansible_include_vars_os_family: true
ansible_include_vars_distribution: true
ansible_include_vars_environment: true
ansible_include_vars_user: true

ansible_environment: ""

ansible_download_cache_path: "~/.cache/ansible/downloads"
ansible_use_download_cache: false

apt_cache_valid_time: 3600

git_repositories:
  projects: {}
