#!/usr/bin/with-contenv sh

# see: https://coder.com/docs/code-server/latest/guide

cd /opt/code-server
exec s6-setuidgid {{ code_server.user | default('root') }}:{{ code_server.group | default('root') }} \
  env VSCODE_IPC_HOOK_CLI= \
    code-server \
      {{ ( "--config=" ~ "'" ~ code_server.config_path ~ "'") if (code_server.config_path | default(false)) }} \
      --disable-update-check \
      --disable-telemetry \
        {{ code_server.workdir | default('/workspace') }}
