---
linuxbrew:
  state: "present"
  taps:
    - "homebrew/bundle"
    - "homebrew/core"
    #- "linuxbrew/xorg"
  packages:
    # the asciinema package depends on python3 and should therefore be installed with pip(x)
    # - "asciinema"
    # the awscli package installs MASSIVE amounts of dependencies
    #- "awscli"
    - "bash"
    - "bash-completion@2"
    - "bat"
    - "bats-core"
    #- "diff-so-fancy"
    - "direnv"
    - "diskus"
    - "docker"
    - "docker-ls"
    - "exa"
    - "fd"
    #- "ffsend"
    - "fzf"
    - "git"
    #- "git-absorb"
    - "git-delta"
    - "git-extras"
    - "git-fixup"
    - "hadolint"
    #- "helm"
    - "hexyl"
    - "hub"
    - "hyperfine"
    - "jo"
    - "jq"
    #- "k3d"
    #- "kubernetes-cli"
    #- "kubectx"
    #- "kustomize"
    - "lf"
    - "lnav"
    - "lsd"
    - "minio-mc"
    #- "packer"
    - "pup"
    - "restic"
    - "ripgrep"
    - "sd"
    - "shfmt"
    # "spaceman-diff" installs a LOT of dependencies
    #- "spaceman-diff"
    - "starship"
    - "tealdeer"
    - "terraform"
    - "terragrunt"
    - "terraform-inventory"
    - "tmux"
    # tmuxinator conflicts with the _tmuxinator file in zsh-completions
    # makes the playbook fail
    #- "tmuxinator"
    - "tokei"
    - "watchexec"
    #- "xsv"
    - "yq"
    - "zsh"
    - "zsh-completions"
