---
- name: "watchexec:set_fact:watchexec_release"
  block:
    - name: "watchexec:sect_fact:watchexec_release:from:github"
      when: "watchexec_release is not defined"
      block:
        - name: "watchexec:get/latest-release"
          github_release:
            user: "{{ watchexec.github.user }}"
            repo: "{{ watchexec.github.repo }}"
            action: "latest_release"
          register: "watchexec_release"
          until: "watchexec_release is succeeded"
          retries: "{{ ansible_retry_count | int }}"
          delay: "{{ ansible_retry_delay | int }}"
          changed_when: "watchexec_release.tag"
          failed_when: "not watchexec_release.tag"
        - name: "watchexec:cache_fact:watchexec_release.tag"
          set_fact:
            watchexec_release: '{"tag": "{{ watchexec_release.tag }}"}'
            cacheable: true
  rescue:
    - name: "watchexec:set_fact:watchexec_release:from:defaults"
      set_fact:
        watchexec_release: '{"tag": "{{ watchexec.github.tag }}"}'
        cacheable: false

- name: "watchexec:set_fact:download:filename"
  set_fact:
    watchexec_download_filename: >-
      {{
        'watchexec-'
        + watchexec_release.tag
        + '-x86_64-unknown-linux-gnu.deb'
      }}
- name: "watchexec:set_fact:download:url|cache_path"
  set_fact:
    watchexec_download_url: >-
      {{
        'https://github.com/'
        + watchexec.github.user
        + '/'
        + watchexec.github.repo
        + '/releases/download/'
        + watchexec_release.tag
        + '/'
        + watchexec_download_filename
      }}

- name: "watchexec:cache"
  when: "(ansible_use_download_cache | bool)"
  block:
    - name: "watchexec:set_fact:cache:path"
      set_fact:
        watchexec_download_cache_path: >-
          {{
            ansible_download_cache_path
            + '/'
            + watchexec_download_filename
          }}
    - name: "watchexec:stat:cache:path"
      stat:
        path: "{{ watchexec_download_cache_path }}"
      register: "watchexec_download_cache_file"
    - name: "watchexec:cache:update"
      when: "not watchexec_download_cache_file.stat.exists"
      block:
        - name: "watchexec:file:cache:directory"
          file:
            state: "directory"
            path: "{{ ansible_download_cache_path }}"
            mode: "750"
        - name: "watchexec:get_url:cache:download"
          get_url:
            url: "{{ watchexec_download_url }}"
            dest: "{{ watchexec_download_cache_path }}"
            mode: "750"
          register: "watchexec_download_result"
          failed_when: "(watchexec_download_result is failed)"
          until: "(watchexec_download_result is succeeded)"
          retries: "{{ ansible_retry_count | int }}"
          delay: "{{ ansible_retry_delay | int }}"
- name: "watchexec:apt:deb:install"
  become: true
  apt:
    deb: >-
      {{
        (ansible_use_download_cache | bool)
        | ternary(
            watchexec_download_cache_path,
            watchexec_download_url
          )
      }}
  register: "watchexec_apt_result"
  failed_when: "(watchexec_apt_result is failed) and (not (watchexec_apt_result.msg.find('already installed') > -1))"
  until: "(watchexec_apt_result is succeeded)"
  retries: "{{ ansible_retry_count | int }}"
  delay: "{{ ansible_retry_delay | int }}"
