---
- name: "zola:set_fact:zola_release"
  block:
    - name: "zola:sect_fact:zola_release:from:github"
      when: "zola_release is not defined"
      block:
        - name: "zola:get/latest-release"
          github_release:
            user: "{{ zola.github.user }}"
            repo: "{{ zola.github.repo }}"
            action: "latest_release"
          register: "zola_release"
          until: "zola_release is succeeded"
          retries: "{{ ansible_retry_count | int }}"
          delay: "{{ ansible_retry_delay | int }}"
          changed_when: "zola_release.tag"
          failed_when: "not zola_release.tag"
        - name: "zola:cache_fact:zola_release.tag"
          set_fact:
            zola_release: '{"tag": "{{ zola_release.tag }}"}'
            cacheable: true
  rescue:
    - name: "zola:set_fact:zola_release:from:defaults"
      set_fact:
        zola_release: '{"tag": "{{ zola.github.tag }}"}'
        cacheable: false

- name: "zola:version:local"
  command: "~/.local/bin/zola --version"
  register: "zola_version"
  failed_when: false
  changed_when: false

- when: >-
    (zola_version.rc != 0)
    or
    (
      zola_version.stdout|regex_search('(\\d+(\\.\\d+){2,})')
      is
      version(zola_release.tag[1:], operator='lt', strict=true)
    )
  block:
    - name: "zola:mktemp"
      tempfile:
        state: "directory"
        suffix: "zola"
      register: "zola_tmp_dir"

    - name: "zola:unarchive"
      unarchive:
        src: >-
          {{
            "https://github.com" ~
            "/" ~ zola.github.user ~
            "/" ~ zola.github.repo ~
            "/releases/download" ~
            "/" ~ zola_release.tag ~
            "/zola-" ~ zola_release.tag ~ "-x86_64-unknown-linux-gnu.tar.gz"
          }}
        remote_src: true
        dest: "{{ zola_tmp_dir.path }}"
      register: "zola_download"
      until: "zola_download is succeeded"
      retries: "{{ ansible_retry_count | int }}"
      delay: "{{ ansible_retry_delay | int }}"

    - name: "zola:copy"
      copy:
        remote_src: true
        src: "{{ zola_tmp_dir.path }}/zola"
        dest: "~/.local/bin/zola"
        mode: "750"
