#!/usr/bin/with-contenv sh

exec 2>&1
export PHP_INI_SCAN_DIR=/usr/local/etc/php/php-fpm.php.ini.d
exec php-fpm \
    -c /usr/local/etc/php/php-fpm.php.ini \
    --fpm-config /usr/local/etc/php-fpm.conf
