# yaml-language-server: $schema=https://github.com/ansible-community/schemas/raw/main/f/ansible-tasks.json
- name: 'nginx-prometheus-exporter:unarchive'
  become: true
  ansible.builtin.unarchive:
    # example url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.10.0/nginx-prometheus-exporter_0.10.0_linux_amd64.tar.gz
    src: >-
      {{
        'https://github.com/nginxinc/nginx-prometheus-exporter/releases/download'
        ~ '/v' ~ nginx_prometheus_exporter.version
        ~ '/'
          ~ 'nginx-prometheus-exporter-'
          ~ nginx_prometheus_exporter.version
          ~ '.linux-'
          ~ ('amd64' if (ansible_architecture == 'x86_64') else 'arm64')
          ~ '.tar.gz'
      }}
    extra_opts:
      - '--strip-components=1'
    include:
     - >-
        {{
          'nginx-prometheus-exporter-'
          ~ nginx_prometheus_exporter.version
          ~ '.linux-'
          ~ ('amd64' if (ansible_architecture == 'x86_64') else 'arm64')
          ~ '/nginx-prometheus-exporter'
        }}
    dest: /usr/local/bin
    creates: '/usr/local/bin/nginx-prometheus-exporter'
    list_files: true
    remote_src: true
  register: "nginx_prometheus_exporter_download"
  until: "nginx_prometheus_exporter_download is succeeded"
  retries: "{{ ansible_retry_count | int }}"
  delay: "{{ ansible_retry_delay | int }}"
- name: 'nginx-prometheus-exporter:file:absent:/usr/local/bin/nginx-prometheus-exporter'
  become: true
  when: '"absent" == nginx_prometheus_exporter.state'
  ansible.builtin.file:
    path: '/usr/local/bin/nginx-prometheus-exporter'
    state: absent
