---
- name: "ripgrep:set_fact:ripgrep_release"
  block:
    - name: "ripgrep:sect_fact:ripgrep_release:from:github"
      when: "ripgrep_release is not defined"
      block:
        - name: "ripgrep:get/latest-release"
          github_release:
            user: "{{ ripgrep.github.user }}"
            repo: "{{ ripgrep.github.repo }}"
            action: "latest_release"
          register: "ripgrep_release"
          until: "ripgrep_release is succeeded"
          retries: "{{ ansible_retry_count | int }}"
          delay: "{{ ansible_retry_delay | int }}"
          changed_when: "ripgrep_release.tag"
          failed_when: "not ripgrep_release.tag"
        - name: "ripgrep:cache_fact:ripgrep_release.tag"
          set_fact:
            ripgrep_release: '{"tag": "{{ ripgrep_release.tag }}"}'
            cacheable: true
  rescue:
    - name: "ripgrep:set_fact:ripgrep_release:from:defaults"
      set_fact:
        ripgrep_release: '{"tag": "{{ ripgrep.github.tag }}"}'
        cacheable: false

- name: "ripgrep:set_fact:download:filename"
  set_fact:
    ripgrep_download_filename: >-
      {{
        ripgrep.github.repo
        + '_'
        + ripgrep_release.tag
        + '_amd64.deb'
      }}
- name: "ripgrep:set_fact:download:url|cache_path"
  set_fact:
    ripgrep_download_url: >-
      {{
        'https://github.com/'
        + ripgrep.github.user
        + '/'
        + ripgrep.github.repo
        + '/releases/download/'
        + ripgrep_release.tag
        + '/'
        + ripgrep_download_filename
      }}

- name: "ripgrep:cache"
  when: "( ansible_use_download_cache | bool )"
  block:
    - name: "ripgrep:set_fact:cache:path"
      set_fact:
        ripgrep_download_cache_path: >-
          {{
            ansible_download_cache_path
            + '/'
            + ripgrep_download_filename
          }}
    - name: "ripgrep:stat:cache:path"
      stat:
        path: "{{ ripgrep_download_cache_path }}"
      register: "ripgrep_download_cache_file"
    - name: "ripgrep:cache:update"
      when: "not ripgrep_download_cache_file.stat.exists"
      block:
        - name: "ripgrep:file:cache:directory"
          file:
            state: "directory"
            path: "{{ ansible_download_cache_path }}"
            mode: "750"
        - name: "ripgrep:get_url:cache:download"
          get_url:
            url: "{{ ripgrep_download_url }}"
            dest: "{{ ripgrep_download_cache_path }}"
            mode: "750"
          register: "ripgrep_download_result"
          failed_when: "(ripgrep_download_result is failed)"
          until: "(ripgrep_download_result is succeeded)"
          retries: "{{ ansible_retry_count | int }}"
          delay: "{{ ansible_retry_delay | int }}"
- name: "ripgrep:apt:deb:install"
  become: true
  apt:
    deb: >-
      {{
        (ansible_use_download_cache | bool)
        | ternary(
            ripgrep_download_cache_path,
            ripgrep_download_url
          )
      }}
  register: "ripgrep_apt_result"
  failed_when: "(ripgrep_apt_result is failed) and (not (ripgrep_apt_result.msg.find('already installed') > -1))"
  until: "(ripgrep_apt_result is succeeded)"
  retries: "{{ ansible_retry_count | int }}"
  delay: "{{ ansible_retry_delay | int }}"
