alertmanager:
  state: present
  # see: https://github.com/prometheus/alertmanager/releases
  version: '0.23.0'
  github:
    user: prometheus
    repo: alertmanager
  installation:
    directory: /opt/alertmanager
    owner: root
    group: alertmanager
    mode:
      binary: u=rwx,g=rx,o=
      config: u=rw,g=r,o=
    link:
      dest: /usr/local/bin
      owner: root
      group: alertmanager
  user:
    name: alertmanager
    uid: 301
    group:
      name: alertmanager
      gid: 301
    home:
      path: '/opt/alertmanager'
      owner: root
      group: alertmanager
      mode: 'u=rX,g=rX,o='
    shell: /usr/sbin/nologin
    system: true
    groups: []
  config_file: /opt/alertmanager/alertmanager.yml
  components:
    - alertmanager
    # alternative installation:
    # go get github.com/prometheus/alertmanager/cmd/amtool
    # example usage: https://github.com/prometheus/alertmanager#examples
    - amtool
  config:
  # documentation: https://prometheus.io/docs/alerting/latest/configuration/#configuration
  # example config: https://github.com/prometheus/alertmanager/blob/main/doc/examples/simple.yml
  # debug routes: https://www.prometheus.io/webtools/alerting/routing-tree-editor/
    global:
      resolve_timeout: 1m
      # 127.0.0.1:1025 is the default local mailhog instance
      smtp_smarthost: '127.0.0.1:1025'
      smtp_from: 'alertmanager@localost'
      smtp_auth_username: ''
      smtp_auth_identity: ''
      smtp_auth_password: ''
      # http_config:
      # see: https://prometheus.io/docs/alerting/latest/configuration/#http_config
    route:
    # see: https://prometheus.io/docs/alerting/latest/configuration/#route
      receiver: 'email'
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 10m
      # group_by: [cluster, alertname]
    receivers:
      - name: webhook
        webhook_configs:
          - url: 'http://localhost/alerts'
      - name: 'email'
        email_configs:
          - to: 'alertmanager-alerts@localhost'
            send_resolved: true
    templates:
    # The directory/glob from which notification templates are read.
    # test: amtool template render --template.glob='/foo/bar/*.tmpl' --template.text='{{ template "slack.default.markdown.v1" . }}'
    # for slack templates - see: https://juliusv.com/promslack/
      - '/etc/alertmanager/template/*.tmpl'
  templates: {}
