---
alternatives:
  - name: "vi"
    priority: "80"
    link: "/usr/bin/vi"
    source: "/home/linuxbrew/.linuxbrew/bin/nvim"
    state: "present"
  - name: "vim"
    priority: "80"
    link: "/usr/bin/vim"
    source: "/home/linuxbrew/.linuxbrew/bin/nvim"
    state: "present"
  - name: "docker-compose"
    priority: "80"
    link: "/usr/bin/docker-compose"
    source: "/usr/local/bin/compose-switch"
    state: "present"
