---
apt:
  packages:
    # ---- packages to be installed ---
    - name: openssh-client
      # provides "ssh" and "ssh-add" commands
      state: present
    - name: openssh-server
      # we install openssh-server to be able to access a devcontainer remotely
      # i.e. as a VSCode devcontainer with the Remote SSH extension
      state: present
    - { name: "htop", state: "present" }
    # ---- packages that shall be absent last ---
    - { name: "memtest86+", state: "absent" }
    - { name: "ruby", state: "absent" }
    - { name: "golang", state: "absent" }
    - { name: "nodejs", state: "absent" }
    # `gedebi-core` installs .deb packages and together with their dependencies
    # not needed as modern versions of apt[-get] provide the same functionality
    # Depends: python3-apt
    # -> Leads to undesired installation of python via apt in containers
    #
    # example: (the dot is required to prevent installing literal package by name)
    # sudo apt -y install ./package.deb
    # sudo dpkg -i /path/to/package.deb; sudo apt-get install -f
    - { name: "gdebi-core", state: "absent" }
    # Depends: python3
    # -> Leads to undesired installation of python via apt in containers
    - { name: "lsb-release", state: "absent" }
