# yaml-language-server: $schema=https://github.com/ansible-community/schemas/raw/main/f/ansible-tasks.json
- name: 'metricbeat:deb'
  become: true
  ansible.builtin.apt:
    state: '{{ metricbeat.state }}'
    deb: >-
      {{
        "https://artifacts.elastic.co/downloads/beats/filebeat/"
        ~ 'filebeat'
        ~ '-'
        ~ filebeat.version
        ~ '-'
        ~ ("amd64" if (ansible_architecture == "x86_64") else 'arm64')
        ~ '.deb'
      }}
  register: "metricbeat_download"
  until: "metricbeat_download is succeeded"
  retries: "{{ ansible_retry_count | int }}"
  delay: "{{ ansible_retry_delay | int }}"
