- name: '[packetbeat]'
  become: true
  block:
    - name: 'packetbeat:apt:dependencies'
      ansible.builtin.apt:
        pkg:
        - libpcap2
      register: "packetbeat_apt_dependencies"
      until: "packetbeat_apt_dependencies is succeeded"
      retries: "{{ ansible_retry_count | int }}"
      delay: "{{ ansible_retry_delay | int }}"
    - name: 'packetbeat:apt:deb'
      ansible.builtin.apt:
        state: '{{ packetbeat.state }}'
        deb: >-
          {{
            "https://artifacts.elastic.co/downloads/beats/packetbeat/"
            ~ 'packetbeat'
            ~ '-'
            ~ packetbeat.version
            ~ '-'
            ~ ("amd64" if (ansible_architecture == "x86_64") else 'arm64')
            ~ '.deb'
          }}
      register: "packetbeat_deb_package"
      until: "packetbeat_deb_package is succeeded"
      retries: "{{ ansible_retry_count | int }}"
      delay: "{{ ansible_retry_delay | int }}"
