- name: 'cachetool:get_url'
  become: true
  ansible.builtin.get_url:
    # example url: https://github.com/gordalina/cachetool/releases/download/8.3.0/cachetool.phar
    url: >-
      {{
        "https://github.com/gordalina/cachetool/releases/download"
        ~ "/" ~ cachetool.version
        ~ "/cachetool.phar"
      }}
    dest: /usr/local/bin/cachetool
    owner: root
    group: root
    mode: '0555'
