# yaml-language-server: $schema=https://github.com/ansible-community/schemas/raw/main/f/ansible-tasks.json
- name: 'rest-server:unarchive'
  become: true
  ansible.builtin.unarchive:
    src: >-
      {{
        'https://github.com/restic/rest-server/releases/download'
        ~ '/v' ~ rest_server.version ~ '/'
        ~ 'rest-server_'
        ~ rest_server.version
        ~ '_linux_'
        ~ ('amd64' if (ansible_architecture == 'x86_64') else 'arm64')
        ~ '.tar.gz'
      }}
    extra_opts:
      - '--strip-components=1'
    include:
     - >-
        {{
          'rest-server_'
          ~ rest_server.version
          ~ '_linux_'
          ~ ('amd64' if (ansible_architecture == 'x86_64') else 'arm64')
          ~ '/rest-server'
        }}
    dest: /usr/local/bin
    creates: '/usr/local/bin/rest-server'
    list_files: true
    remote_src: true
  register: "rest_server_download"
  until: "rest_server_download is succeeded"
  retries: "{{ ansible_retry_count | int }}"
  delay: "{{ ansible_retry_delay | int }}"
