# yaml-language-server: $schema=https://github.com/ansible-community/schemas/raw/main/f/ansible-tasks.json
- name: '[xdebug_info:state=present]'
  when: '"present" == xdebug_info.state'
  become: true
  block:
    - name: 'xdebug_info:file:install_dir'
      ansible.builtin.file:
        state: 'directory'
        path: '{{ xdebug_info.install_dir }}'
        owner: '{{ xdebug_info.owner }}'
        group: '{{ xdebug_info.group }}'
        mode: '{{ xdebug_info.mode }}'
    - name: 'xdebug_info:template:script'
      ansible.builtin.lineinfile:
        create: true
        state: present
        regexp: '^<\?php'
        line: '<?php xdebug_info();'
        dest: '{{ xdebug_info.install_dir ~ "/index.php" }}'
        owner: '{{ xdebug_info.owner }}'
        group: '{{ xdebug_info.group }}'
        mode: '{{ xdebug_info.mode }}'
- name: '[xdebug_info:state=present]'
  when: '"absent" == xdebug_info.state'
  become: true
  ansible.builtin.file:
    path: '{{ xdebug_info.install_dir }}'
    state: 'absent'
