- name: "s6:file:directory:/etc/services.d/${service}/{log,env}"
  become: true
  ansible.builtin.file:
    path: '{{ "/etc/services.d/" ~ item[0] ~ "/" ~ item[1] }}'
    state: directory
    owner: root
    group: root
    mode: '550'
  loop: '{{ s6.services | product(["log", "env"]) | list }}'

- name: "s6:template:/etc/services.d/${service}/*"
  become: true
  ansible.builtin.template:
    src: '{{ "s6/" ~ item[0] ~ "/services.d/" ~ item[0] ~ "/" ~ item[1] }}'
    dest: '{{ "/etc/services.d/" ~ item[0] ~ "/" ~ item[1] }}'
    owner: root
    group: root
    mode: '550'
  loop: '{{ s6.services | product(["run", "log/run"]) | list }}'
