---
- name: 'journald:config:lineinfile:/etc/systemd/journald.conf'
  become: true
  lineinfile:
    path: '/etc/systemd/journald.conf'
    regexp: '^SystemMaxUse='
    line: 'SystemMaxUse=100'

- name: 'journald:restart:service'
  become: true
  systemd:
    name: 'systemd-journald'
    state: 'restarted'
