# see: https://min.io/download#/linux
# see: https://dl.min.io/server/minio/release/
- name: 'minio:get_url'
  become: true
  ansible.builtin.get_url:
    url: >-
      {{
        "https://dl.min.io/server/minio/release"
        ~ "/linux-" ~ ("amd64" if (ansible_architecture == "x86_64") else 'arm64')
        ~ "/archive"
        ~ "/minio.RELEASE." ~ minio.release
      }}
    dest: /usr/local/bin/minio
    owner: root
    group: root
    mode: '755'
