---
openssh_client:
  state: 'present'
  known_hosts:
    user:
      become: false
      path: "~/.ssh/known_hosts"
      absent: {}
      present:
        "github.com": "github.com,140.82.118.1,140.82.118.2,140.82.118.3,140.82.118.4 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
        "bitbucket.org": "bitbucket.org,18.205.93.0,18.205.93.1,18.205.93.2,18.205.93.3 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw=="
  config_file:
    extension: ".ssh_config"
    user: "~/.ssh/config"
    global: "/etc/ssh/ssh_config"
  config:
    user: {}
    global:
      "90-github":
        - "Host github gb":
            - HostName: "github.com"
            - User: "git"
            - PasswordAuthentication: "No"
      "90-bitbucket":
        - "Host bitbucket bb":
            - HostName: "bitbucket.org"
            - User: "git"
            - PasswordAuthentication: "No"
      "90-gitlab":
        - "Host gitlab gl":
            - HostName: "gitlab.com"
            - User: "git"
            - PasswordAuthentication: "No"
