---
- name: "zsh:package:install"
  tags:
    - zsh[package]
  become: true
  package:
    name: "zsh"
    state: "present"

- name: "zsh:file:directory:~/.local/[usr/]/share/zsh/{functions,history,plugins,completions}"
  file:
    path: "{{ item }}"
    mode: "0700"
    state: "directory"
  loop:
    - "~/.local/share/zsh/history"
    - "~/.local/share/zsh/completions"
    - "~/.local/share/zsh/functions"
    - "~/.local/usr/share/zsh/functions"
    - "~/.local/usr/share/zsh/completions"
  tags:
    - config[*]
    - zsh[config]
    - zsh[directory-structure]

- name: "zsh:file:copy:~/.zshrc"
  template:
    src: "zsh/.zshrc"
    dest: "~/.zshrc"
    mode: "0700"
  tags:
    - config[*]
    - zsh[config]

- name: "zsh[plugins]"
  tags:
    - zsh[plugins]
  become: true
  block:
    - name: "zsh[plugins]:file:directory:/usr/share/zsh/plugins"
      ansible.builtin.file:
        path: '/usr/share/zsh/plugins/zsh-defer'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'
    - name: "zsh[plugins]:get_url:zsh-defer"
      ansible.builtin.get_url:
        url: 'https://raw.githubusercontent.com/romkatv/zsh-defer/master/zsh-defer.plugin.zsh'
        dest: '/usr/share/zsh/plugins/zsh-defer/zsh-defer.plugin.zsh'
        owner: 'root'
        group: 'root'
        mode: '0744'

- name: "zsh[global-zshenv]"
  tags:
    - zsh[global-zshenv]
  block:
    - name: "zsh:stat:/etc/zsh/zshenv"
      stat:
        path: "/etc/zsh/zshenv"
      register: "zsh_global_zshenv"
    - name: "zsh:file:touch:/etc/zsh/zshenv"
      when: "not zsh_global_zshenv.stat.exists"
      file:
        path: "/etc/zsh/zshenv"
        state: "touch"
    - name: "zsh:lineinfile:/etc/zsh/zshenv"
      become: true
      lineinfile:
        path: "/etc/zsh/zshenv"
        line: "zsh-newuser-install() { :; }"
        state: "present"
