---
- name: "lscolors:set_fact:lscolors_release"
  block:
    - name: "lscolors:sect_fact:lscolors_release:from:github"
      when: "lscolors_release is not defined"
      block:
        - name: "lscolors:get/latest-release"
          github_release:
            user: "{{ lscolors.github.user }}"
            repo: "{{ lscolors.github.repo }}"
            action: "latest_release"
          register: "lscolors_release"
          until: "lscolors_release is succeeded"
          retries: "{{ ansible_retry_count | int }}"
          delay: "{{ ansible_retry_delay | int }}"
          changed_when: "lscolors_release.tag"
          failed_when: "not lscolors_release.tag"
        - name: "lscolors:cache_fact:lscolors_release.tag"
          set_fact:
            lscolors_release: '{"tag": "{{ lscolors_release.tag }}"}'
            cacheable: true
  rescue:
    - name: "lscolors:set_fact:lscolors_release:from:defaults"
      set_fact:
        lscolors_release: '{"tag": "{{ lscolors.github.tag }}"}'
        cacheable: false

- name: "lscolors:set_fact:download:filename"
  set_fact:
    lscolors_download_filename: >-
      {{
        'lscolors_'
        + lscolors_release.tag[1:]
        + '_amd64.deb'
      }}
- name: "lscolors:set_fact:download:url|cache_path"
  set_fact:
    lscolors_download_url: >-
      {{
        'https://github.com/'
        + lscolors.github.user
        + '/'
        + lscolors.github.repo
        + '/releases/download/'
        + lscolors_release.tag
        + '/'
        + lscolors_download_filename
      }}

- name: "lscolors:cache"
  when: "( ansible_use_download_cache | bool )"
  block:
    - name: "lscolors:set_fact:cache:path"
      set_fact:
        lscolors_download_cache_path: >-
          {{
            ansible_download_cache_path
            + '/'
            + lscolors_download_filename
          }}
    - name: "lscolors:stat:cache:path"
      stat:
        path: "{{ lscolors_download_cache_path }}"
      register: "lscolors_download_cache_file"
    - name: "lscolors:cache:update"
      when: "not lscolors_download_cache_file.stat.exists"
      block:
        - name: "lscolors:file:cache:directory"
          file:
            state: "directory"
            path: "{{ ansible_download_cache_path }}"
            mode: "750"
        - name: "lscolors:get_url:cache:download"
          get_url:
            url: "{{ lscolors_download_url }}"
            dest: "{{ lscolors_download_cache_path }}"
            mode: "750"
          register: "lscolors_download_result"
          failed_when: "(lscolors_download_result is failed)"
          until: "(lscolors_download_result is succeeded)"
          retries: "{{ ansible_retry_count | int }}"
          delay: "{{ ansible_retry_delay | int }}"
- name: "lscolors:apt:deb:install"
  become: true
  apt:
    deb: >-
      {{
        (ansible_use_download_cache | bool)
        | ternary(
            lscolors_download_cache_path,
            lscolors_download_url
          )
      }}
  register: "lscolors_apt_result"
  failed_when: "(lscolors_apt_result is failed) and (not (lscolors_apt_result.msg.find('already installed') > -1))"
  until: "(lscolors_apt_result is succeeded)"
  retries: "{{ ansible_retry_count | int }}"
  delay: "{{ ansible_retry_delay | int }}"
