# yaml-language-server: $schema=https://github.com/ansible-community/schemas/raw/main/f/ansible-tasks.json
- name: 'php-fpm_exporter:unarchive'
  become: true
  when: '"present" == php_fpm_exporter.state'
  ansible.builtin.get_url:
    url: >-
      {{
        'https://github.com/hipages/php-fpm_exporter/releases/download'
        ~ '/v' ~ php_fpm_exporter.version
        ~ '/'
          ~ 'php-fpm_exporter'
          ~ '_'
          ~ php_fpm_exporter.version
          ~ '_linux_'
          ~ ('amd64' if (ansible_architecture == 'x86_64') else 'arm64')
      }}
    dest: '/usr/local/bin/php-fpm_exporter'
    owner: root
    group: root
    mode: '755'
  register: "php_fpm_exporter_download"
  until: "php_fpm_exporter_download is succeeded"
  retries: "{{ ansible_retry_count | int }}"
  delay: "{{ ansible_retry_delay | int }}"
- name: 'php-fpm_exporter:file:absent:/usr/local/bin/php-fpm_exporter'
  become: true
  when: '"absent" == php_fpm_exporter.state'
  ansible.builtin.file:
    path: '/usr/local/bin/php-fpm_exporter'
    state: absent
