---
- name: 'filebeat[package]'
  # see: https://www.elastic.co/guide/en/beats/filebeat/current/setup-repositories.html
  become: true
  tags:
    - filebeat[package]
  block:
    - name: 'filebeat:apt_key'
      ansible.builtin.apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: '{{ filebeat.state }}'
      register: "filebeat_apt_key"
      until: "filebeat_apt_key is succeeded"
      retries: "{{ ansible_retry_count | int }}"
      delay: "{{ ansible_retry_delay | int }}"
    - name: 'filebeat:apt_repository'
      ansible.builtin.apt_repository:
        state: '{{ filebeat.state }}'
        repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
        filename: 'elastic-7.x'
        install_python_apt: false
        update_cache: true
      register: "filebeat_apt_repository"
      until: "filebeat_apt_repository is succeeded"
      retries: "{{ ansible_retry_count | int }}"
      delay: "{{ ansible_retry_delay | int }}"
    - name: 'filebeat:apt:package'
      ansible.builtin.apt:
        state: '{{ filebeat.state }}'
        name: 'filebeat={{ filebeat.version }}'
      register: "filebeat_apt_package"
      until: "filebeat_apt_package is succeeded"
      retries: "{{ ansible_retry_count | int }}"
      delay: "{{ ansible_retry_delay | int }}"
- name: 'filebeat[config]'
  become: true
  tags:
    - filebeat[config]
  block:
    - name: 'filebeat:file/directory:config-dir'
      ansible.builtin.file:
        path: '/usr/share/filebeat'
        state: 'directory'
        owner: root
        group: root
        mode: 0755
    - name: 'filebeat:template:config'
      ansible.builtin.template:
        src: "filebeat/filebeat.yml.j2"
        dest: "/etc/filebeat/filebeat.yml"
        mode: "0644"
