- name: "redis:apt"
  ansible.builtin.apt:
    state: "{{ redis.state }}"
    package: redis
- name: "redis:file:directory:/etc/redis/"
  ansible.builtin.file:
    path: /etc/redis
    state: "directory"
    owner: root
    group: root
    mode: '0755'
- name: "redis:template:/etc/redis/redis.conf"
  ansible.builtin.template:
    src: "redis/redis.conf.j2"
    dest: "/etc/redis/redis.conf"
    owner: root
    group: root
    mode: "0744"
